-- CreateEnum
CREATE TYPE "DegreeType" AS ENUM ('CERTIFICATE', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE');

-- CreateEnum
CREATE TYPE "EnrollmentStatus" AS ENUM ('ACTIVE', 'DROPPED', 'COMPLETED', 'WAITLISTED');

-- CreateEnum
CREATE TYPE "RequirementType" AS ENUM ('CORE', 'ELECTIVE', 'GENERAL_EDUCATION', 'MAJOR');

-- CreateEnum
CREATE TYPE "StudentProgramStatus" AS ENUM ('ACTIVE', 'GRADUATE', 'WITHDRAWN', 'SUSPENDED', 'TRANSFERRED');
